environments:
  development:
  staging:

---

helmDefaults:
  wait: true
  timeout: 600

releases:
  - name: social-app-admin
    namespace: xiangjiandao
    chart: oci://ghcr.io/xjdao2025/social-app-admin
    version: {{ requiredEnv "VERSION_NUMBER" }}
    values:
      - ./values/{{ .Environment.Name }}.yaml