export enum SMS_CODE_TYPE  {
  LOGIN = 1,
  RESET_PASS = 2,
  REGISTER  ,
  CHANGE_EMAIL,
  ADD_ACCOUNT,
  WITHDRAW = 7,
}


export enum CURRENCY_TYPE_CODE {
  USDT = 1,
  USDC = 2,
  USDI = 3
}

export enum USER_ROLE_TYPE {
  ADMIN = 1,
  OPERATION
}

export const CURRENCY_NAME = {
  [CURRENCY_TYPE_CODE.USDT]: 'USDT',
  [CURRENCY_TYPE_CODE.USDC]: 'USDC',
  [CURRENCY_TYPE_CODE.USDI]: 'USDI',
}