// Do not modify this file, it is auto generated by vite-plugin-i18n-resource
import "./hmr";
{{each item in data}}
{{each module in item.modules}}
import {{module.id}} from "{{module.path}}";
{{/each}}
{{/each}}

const resources = {
  {{each item in data}}
  "{{item.locale}}": {
    {{each module in item.modules}}
    "{{module.ns}}": {{module.id}},
    {{/each}}
  },
  {{/each}}
}

export default resources;