// Do not modify this file, it is auto generated by vite-plugin-i18n-resource
import "./hmr";
import en_US_component_captcha from "./en-US/component.captcha.json";
import en_US_component_chain_hash from "./en-US/component.chain-hash.json";
import en_US_component_empty from "./en-US/component.empty.json";
import en_US_component_login from "./en-US/component.login.json";
import en_US_component_verification from "./en-US/component.verification.json";
import en_US_components from "./en-US/components.json";
import en_US_page_change_password from "./en-US/page.change-password.json";
import en_US_page_users from "./en-US/page.users.json";
import en_US_translation from "./en-US/translation.json";
import zh_CN_component_captcha from "./zh-CN/component.captcha.json";
import zh_CN_component_chain_hash from "./zh-CN/component.chain-hash.json";
import zh_CN_component_empty from "./zh-CN/component.empty.json";
import zh_CN_component_login from "./zh-CN/component.login.json";
import zh_CN_component_verification from "./zh-CN/component.verification.json";
import zh_CN_components from "./zh-CN/components.json";
import zh_CN_page_change_password from "./zh-CN/page.change-password.json";
import zh_CN_page_users from "./zh-CN/page.users.json";
import zh_CN_translation from "./zh-CN/translation.json";

const resources = {
  "en-US": {
    "component.captcha": en_US_component_captcha,
    "component.chain-hash": en_US_component_chain_hash,
    "component.empty": en_US_component_empty,
    "component.login": en_US_component_login,
    "component.verification": en_US_component_verification,
    "components": en_US_components,
    "page.change-password": en_US_page_change_password,
    "page.users": en_US_page_users,
    "translation": en_US_translation,
  },
  "zh-CN": {
    "component.captcha": zh_CN_component_captcha,
    "component.chain-hash": zh_CN_component_chain_hash,
    "component.empty": zh_CN_component_empty,
    "component.login": zh_CN_component_login,
    "component.verification": zh_CN_component_verification,
    "components": zh_CN_components,
    "page.change-password": zh_CN_page_change_password,
    "page.users": zh_CN_page_users,
    "translation": zh_CN_translation,
  },
}

export default resources;